module.exports = {
item: [{
    name: "épée de base",
    id: 0,
    emoji:"⚔️",
    stats: {
        force: 5,
        defense: 2,
        magie:  0,
        intelligence: 0,
        vitesse: -3,
        },
    rarity: "Commun",
    type: "Arme",
    food: null,
},
{
    name: "Dague de base",
    id: 1,
    emoji:"🗡️",
    stats: {
        force: 4,
        defense: 1,
        magie:  0,
        intelligence: 0,
        vitesse: -1,
        },
    rarity: "Commun",
    type: "Arme",
    food: null,
},
{
    name: "Arc de base",
    id: 2,
    emoji:"🏹",
    stats: {
        force: 7,
        defense: 0,
        magie: 0,
        intelligence: 0,
        vitesse: -2,
        },
    rarity: "Commun",
    type: "Arme",
    food: null,
},
{
    name: "Bouclier de base",
    id: 3,
    emoji:"🛡",
    stats: {
        force: 1,
        defense: 5,
        magie: 0,
        intelligence: 0,
        vitesse: -2,
        },
    rarity: "Commun",
    type: "Arme",
    food: null,
},
{
    name: "Bouclier de Mana de base",
    id: 4,
    emoji:"💠",
    stats: {
        force: 3,
        defense: 7,
        magie: 4,
        intelligence: 0,
        vitesse: -3,
        },
    rarity: "Peu-commun",
    type: "Arme",
    food: null,
}]  
}; 
